export const UPLOAD_FORM_NAME = 'UploadForm'
export const EDIT_USER_FORM_NAME = 'EditUserForm'
export const LOGIN_FORM_NAME = 'LoginForm'
export const REGISTER_FORM_NAME = 'RegisterForm'
export const PUZZLE_FORM_NAME = 'PuzzleForm'